scalar Point
scalar DateTime
scalar PointInput

"""
User will also contain spaces[], comments[], answers[], questions[]
Drawback: Password is being stored as plain string. Not able to figure out JWT
"""
type User {
	_id: ID!
	name: String!
	email: String!
	password: String!
}

type Mutation {
	createUser(name: String!, email: String!, password: String!): User!
}

type Query {
	userCount: Int! @cypher(statement: "MATCH (u:User) RETURN COUNT(u)")
	user(_id: String!): User
		@cypher(
			statement: """
			MATCH (u {_id: $_id}) RETURN u
			"""
		)
}
